= lib60870 User Guide
Michael Zillgith

== Introduction

lib60870 is a new implementation of the IEC 60870-5-104 protocol for client (master station) and server (controlled station). The library implements all data types of the IEC 60870-5-101/104 specifications. It comes with two flavors which are actually two different implementations that share a similar API:

* *lib60870-C* is an implementation written in the C99 standard. It is designed to be used on resource restricted embedded systems but is easy to use as well.
* *lib60870.NET* is a pure C#/.NET implementation. It is designed to be as easy to use as possible. Since it is using only standardized .NET features it is compatible with Windows systems and the Microsoft .NET implementation as well as on Linux and other operating systems running with Mono.

The client/server API is strictly asynchronous. You send the requests with non-blocking functions and will have to handle the response and other events in callback functions.

== Create a connection

Since an IEC 60870-5-104 connection is based on a TCP client/server connection the connection will be established by the client(master). The server(slave or outstation) is passively waiting for connections.

In C# a connection is simple created by calling a Constructor of the Connection class:

  Connection con = new Connection ("127.0.0.1");

This creates a new Connection object that is ready to connect to the server. If you can live with the default connection parameters (TCP port 2404 and a common set of the IEC 60870-5-104 parameters) you can now simply call the _Connect_ method:

  con.Connect ();

When the connection has been established correctly you can use the connection object to send commands and receive data.

== Sending a read request

The IEC 60870 documents don't recommend this service (cyclical data requests or polling) but it is an easy way to get the required data. You just need to know the common address (CA) and the information object address (IOA) to create the proper request.

  con.SendReadCommand(1 /* CA */, 2001 /* IOA */);

The call is non-blocking. You have to evaluate the response in the ASDUReceivedHandler callback function.

Typically it is expected that the server response contains only the basic data type without timestamps (that is using the message types for a specific data type that does not contain the timestamps)!

== Interrogation

You can also request a group of data items from a slave with a single request. On the master (client) side you can simply use the SendInterrogationCommand method of the Connection object:

  con.SendInterrogationCommand (CauseOfTransmission.ACTIVATION, 1, 20);

The client/master side method signature looks like this:

  public void SendInterrogationCommand(CauseOfTransmission cot, int ca, byte qoi)

The parameter ca is the common address (CA) as in the other methods. The parameter qoi is the "Qualifier of interrogation" (QOI). The value "20" (indicating "station interrogation") for the QOI indicates that it is an request for all data points. Other values for QOI will indicate that the client (master) only wants to receive data from a specific interrogation group.

On the server side you should use the InterrogationHandler delegate (or callback function in the C library) to handle the Interrogation request. Depending on the QOI value your should return different information objects. For a simple system it is enough to only handle station interrogation requests (QOI = 20).

According to the specification the server has to respond the ACTIVATION request from the client with the ACT_CON response followed by ASDUs containing the information objects with the COT = INTERROGATED_BY_STATION. After sending all information objects the server has to send the initial interrogation command message with COT = ACT_TERM to indicate that the transmission of the interrogation data is finished.

[[app-listing]]
[source, csharp]
.Example how to implement an InterrogationHandler in C#
----
  private static bool interrogationHandler(object parameter, ServerConnection connection, ASDU asdu, byte qoi)
  {
    Console.WriteLine ("Interrogation for group " + qoi);

    // send ACT_CON
    connection.SendACT_CON (asdu, false);

    // send information objects
    newAsdu.AddInformationObject (new MeasuredValueScaled (100, -1, new QualityDescriptor ()));
    newAsdu.AddInformationObject (new MeasuredValueScaled (101, 23, new QualityDescriptor ()));
    newAsdu.AddInformationObject (new MeasuredValueScaled (102, 2300, new QualityDescriptor ()));
    connection.SendASDU (newAsdu);

    newAsdu = new ASDU (TypeID.M_ME_TE_1, CauseOfTransmission.INTERROGATED_BY_STATION, false, false, 3, 1, false);
    newAsdu.AddInformationObject(new MeasuredValueScaledWithCP56Time2a(103, 3456, new QualityDescriptor (), new CP56Time2a(DateTime.Now)));
    connection.SendASDU (newAsdu);

    newAsdu = new ASDU (TypeID.M_SP_TB_1, CauseOfTransmission.INTERROGATED_BY_STATION, false, false, 2, 1, false);
    newAsdu.AddInformationObject (new SinglePointWithCP56Time2a (104, true, new QualityDescriptor (), new CP56Time2a (DateTime.Now)));
    connection.SendASDU (newAsdu);

    // send ACT_TERM
    connection.SendACT_TERM (asdu);

    return true;
  }
----

== Spontaneous transmission of messages

For spontaneous message transmission on the server side the API user has to allocate an ASDU object, add Information Objects to the ASDU and put the ASDU into the transmission queue. The transmission queue is a FIFO (first in first out) list. If the queue is full the oldest message will be deleted and replaced by the newly added message. Messages will only be sent if the there is an active client connection. Otherwise the messages will remain in the queue until a connection is activated.

*LIB60870.NET:* The size of the queue is controlled by the property *MaxQueueSize* of the *Server* object in the C# implementation.

*LIB60870-C:* In the C version the queue size is determined by the *maxQueueSize* parameter of the *T104Slave_create* function. If the library is compiled with the _CONFIG_SLAVE_WITH_STATIC_MESSAGE_QUEUE_ option enabled the _maxQueueSize_ parameter will be ignored and the queue will always have the size defined with by _CONFIG_SLAVE_MESSAGE_QUEUE_SIZE_.

*LIB60870.NET:* These are the required steps for the C# implementation:

. Step: Create a new ASDU instance

    ASDU newAsdu = new ASDU (TypeID.M_ME_NB_1, CauseOfTransmission.PERIODIC, false, false, 2, 1, false);

. Step: Add an information object to the ASDU

    newAsdu.AddInformationObject (new MeasuredValueScaled (110, -1, new QualityDescriptor ()));

. Step: Add the ASDU to the transmission queue

    server.EnqueueASDU (newAsdu);

== Clock synchronization procedure

For the clock synchronization procedure the controlling station (master) sends a C_CS_NA_1 ACT message to the controlled station (slave) containing the current valid time information as a CP56Time2a typed time value. The controlled station has to update its internal time and respond with a C_CS_NA_1 ACT_CON message after all queued time-tagged PDUs have been sent.

Clock synchronization of the controlled station can be done with a with the _SendClockSyncCommand_ method of the Connection class.

  CP56Time2a currentTime = new CP56Time2a (DateTime.Now);
  con.SendClockSyncCommand (1 /* CA */, currentTime);

For the C implementation it is only slightly different:

    struct sCP56Time2a currentTime;
    CP56Time2a_createFromMsTimestamp(&currentTime, Hal_getTimeInMs());
    T104Connection_sendClockSyncCommand(con, 1 /* CA */, &currentTime);

Or when using dynamic memory allocation:

  CP56Time2a currentTime = CP56Time2a_createFromMsTimestamp(NULL, Hal_getTimeInMs());
  T104Connection_sendClockSyncCommand(con, 1 /* CA */, currentTime);

== Command procedures

Commands are used to set set points, parameters or trigger some actions at the outstation.

The following command types (data types are available for commands):

* C_SC (single command) - to control binary data (switch...)
* C_DC (double command) - to control binary data with transition state (moving switch...)
* S_RC (step position command) - to control a step position
* S_SE (setpoint command) - to control a set point (scaled value, normalized value, floating point values) - may also be used to set parameters, alarm limits etc.

These command types are also available in a version with a time tag (CP56TIme2a).

There are two different command procedures available. The *direct operate* command procedure and the *select before operate* command procedure.

To send a command for the direct operate command procedure you have to send an ACTIVATION APDU to the outstation.

    Connection con = new Connection ("127.0.0.1");

    con.SendControlCommand (TypeID.C_SC_NA_1, CauseOfTransmission.ACTIVATION, 1,
                  new SingleCommand (5000, true, false, 0));

To issue a single command you have to provide the proper _TypeID (C_SC_NA_1)_ and pass a _SingleCommand_ instance to the _SendControlCommand_ method.

The constructor of SingleCommand has the following signature:

  public SingleCommand (int ioa, bool command, bool selectCommand, int qu)

In order to send a direct operate command the _selectCommand_ parameter should be false. The qualifier (_qu_) should in general be set to 0.

If the command has been successful the outstation will answer with an ACT_CON response message with the _negative flag_ not set. In case the outstation cannot execute the command it will also answer with an ACT_CON response but with the _negative flag_ set. You can check if this flag is set with the IsNegative property of the received ASDU instance.


== Server configuration and setup

To configure and setup an IEC 60870-5-104 server/slave an instance of the _Server_ class is required.

  Server server = new Server ();

After the server instance is created it can be configured

*LIB60870-C:* In the C version a server/slave is represented by the _Slave_ data type. To create a slave instance for IEC 60870-5-104 the _T104Slave_create_ function is required.

  Slave slave = T104Slave_create(NULL, 100, 100);

=== Server mode

From version 0.9.5 the server provides two different modes.

The default mode (_SINGLE_REDUNDANCY_GROUP_) allows only a *single active client connection*. An active client connection is a connection where ASDUs are sent. All other connections are standby connections. There is a single queue for events. Events are also stored when no client is connected or when no connection is active.

The second mode (_CONNECION_IS_REDUNDANCY_GROUP_) allows *multiple active client connections*. Every connection has its own event queue. The event queue will be deleted when the client connection is closed. This mode has to be used when more then one client has to access the application data.

The server mode can be set with the _ServerMode_ property of the _Server_ class.

  server.ServerMode = ServerMode.CONNECION_IS_REDUNDANCY_GROUP;

=== Restrict the number of client connections

The number of clients can be restricted with the _MaxOpenConnections_ property of the _Server_ class.

  server.MaxOpenConnections = 2;

In this case the server will only allow two concurrent client connections.

=== Setting local port and IP address

The default TCP port for IEC 60870-5-104 is 2404. The port can be changed with the _SetLocalPort_ method of the _Server_ class.

  server.SetLocalPort(2405);

Per default the server listens to all local IP addresses. With the _SetLocalAddress_ method of the _Server_ class it is possible to restrict the server to a single local IP address.

  server.SetLocalAddress("192.168.1.50");

=== Set the size of the event queue

The maximum size of the event queue(s) can be set with the _MaxQueueSize_ property of the _Server_ class. The default size is 1000. Each queue entry needs approximately 260 bytes.

    server.MaxQueueSize = 10;

=== Set a connection request handler to restrict the access and track connections

The _ConnectionRequestHandler_ can be used to restrict the access to the server. With the return value the application can allow or deny the connection attempt of a client.

A _ConnectionRequestHandler_ can be set with the _SetConnectionRequestHandler_ method of the _Server_ class. The second parameter is an arbitrary user provided object that will be passed to the handler when it is called. If not needed it can be set to _null_.

  server.SetConnectionRequestHandler (connectionRequestHandler, null);

[[app-listing]]
[source, csharp]
.Example how to implement a ConnectionRequestHandler in C#
----
static bool connectionRequestHandler(object parameter, IPAddress ipAddress)
{
  // Allow only known IP addresses!
  // You can implement your allowed client whitelist here
  if (ipAddress.ToString ().Equals ("127.0.0.1"))
    return true;
  else
    return false;
}
----

In the handler you can optionally check the client IP address against a whitelist of allowed clients or implement a blacklist.

=== Starting/Stopping the server

After the server is configured it can be started with the _Start_ method

  server.Start ();

To deactivate the IEC 60870-5-104 service the server can be stopped with the _Stop_ method.

  server.Stop ();


== lib60870-C specific topics

=== Debug output

The debug output to the console can be enabled by setting _CONFIG_DEBUG_OUTPUT_ to 1. This will enable the debug output by default. The debug output can be disabled my using the function *Lib60870_enableDebugOutput*. The default implementation of the debug output function will print to the console (using printf). If you need to redirect the output the most easy way would be to change the implementation of the debug output *lib60870_debug_print* function in _lib60870_common.c_.

=== Big endian platforms

The library contains a C header file to determine the platform byte order (_src/inc/internal/platform_endian.h_) when using the GCC compiler. This depends on defines that are provided by the C compiler. On some older big endian platforms like PowerPC or Coldfire depending on the compiler this may fail. You may have to define

  PLATFORM_IS_BIGENDIAN 1

when compiling the library code.

E.g. put

  -DPLATFORM_IS_BIGENDIAN=1

on the GCC command line when the platform byte order is big endian.

=== Configuration options at library compile time

Some configuration options are fixed at compile time of the library code. These options can be found in the file *lib60870_config.h*.

== Advanced topics ==

=== Creating non-standard information object types ===

For lib60870.NET you should derive a new class from the *InformationObject* class.

== Reference information

=== Supported message types

The library supports the following ASDU (application service data unit) types.

.IEC 60870-5-101/104 message types
[width="90%",cols="n,10,1,1",frame="topbot",options="header"]
|==========================
| Message type | Description | C | C#
| M_SP_NA_1(1) | Single point information (BOOLEAN)  | + | +
| M_SP_TA_1(2) | Single point information (BOOLEAN) with CP24Time2a | + | +
| M_DP_NA_1(3) | Double point information (ON/OFF/transient)  | + | +
| M_DP_TA_1(4) | Double point information (ON/OFF/transient) with CP24Time2a  | + | +
| M_ST_NA_1(5) | Step position information (-64 ... 63, is transient)  | + | +
| M_ST_TA_1(6) | Step position information (-64 ... 63, is transient) with CP24Time2a | + | +
| M_BO_NA_1(7) | Bitstring32 (32 bit bitstring)  | + | +
| M_BO_TA_1(8) | Bitstring32 (32 bit bitstring) with CP24Time2a | + | +
| M_ME_NA_1(9) | Normalized measured value (-1.0 ... +1.0)  | + | +
| M_ME_TA_1(10) | Normalized measured value (-1.0 ... +1.0) with CP24Time2a | + | +
| M_ME_NB_1(11) | Scaled measured value (-32768 ... +32767)  | + | +
| M_ME_TB_1(12) | Scaled measured value (-32768 ... +32767) with CP24Time2a | + | +
| M_ME_NC_1(13) | Short measured value (FLOAT32)  | + | +
| M_ME_TC_1(14) | Short measured value (FLOAT32) with CP24Time2a | + | +
| M_IT_NA_1(15) | Integrated totals (INT32 with quality indicators)  | + | +
| M_IT_TA_1(16) | Integrated totals (INT32 with quality indicators) with CP24Time2a | + | +
| M_EP_TA_1(17) | Event of protection equipment | + | +
| M_EP_TB_1(18) | Packed start events of protection equipment | + | +
| M_EP_TC_1(19) | Packed output circuit info | + | +
| M_PS_NA_1(20) | Packed single point with SCD | + | +
| M_ME_ND_1(21) | Normalized measured value (-1.0 ... +1.0) without quality | + | +
| M_SP_TB_1(30) | Single point information (BOOLEAN) with CP56Time2a | + | +
| M_DP_TB_1(31) | Double point information (ON/OFF/transient) with CP56Time2a  | + | +
| M_ST_TB_1(32) | Step position information (-64 ... 63, is transient) with CP56Time2a  | + | +
| M_BO_TB_1(33) | Bitstring32 (32 bit bitstring) with CP56Time2a | + | +
| M_ME_TD_1(34) | Normalized measured value (-1.0 ... +1.0) with CP56Time2a | + | +
| M_ME_TE_1(35) | Scaled measured value (-32768 ... +32767) with CP56Time2a | + | +
| M_ME_TF_1(36) | Short measured value (FLOAT32) with CP56Time2a | + | +
| M_IT_TB_1(37) | Integrated totals (INT32 with quality indicators) with CP56Time2a | + | +
| M_EP_TD_1(38) | Event of protection equipment with CP56Time2a | + | +
| M_EP_TE_1(39) | Packed start events of protection equipment with CP56Time2a | + | +
| M_EP_TF_1(40) | Packed output circuit info with CP56Time2a | + | +
| C_SC_NA_1(45) | Single command (BOOLEAN) | + | +
| C_DC_NA_1(46) | Double command (ON/OFF/transient) | + | +
| C_RC_NA_1(47) | Step command | + | +
| C_SE_NA_1(48) | Setpoint command, normalized value (-1.0 ... +1.0)| + | +
| C_SE_NB_1(49) | Setpoint command, scaled value (-32768 ... +32767) | + | +
| C_SE_NC_1(50) | Setpoint command, short value (FLOAT32)| + | +
| C_BO_NA_1(51) | Bitstring command (32 bit bitstring)  | + | +


| C_SC_TA_1(58) | Single command (BOOLEAN) with CP56Time2a | + | +
| C_DC_TA_1(59) | Double command (ON/OFF/transient) with CP56Time2a | + | +
| C_RC_TA_1(60) | Step command with CP56Time2a | + | +
| C_SE_TA_1(61) | Setpoint command, normalized value (-1.0 ... +1.0) with CP56Time2a| + | +
| C_SE_TB_1(62) | Setpoint command, scaled value (-32768 ... +32767) with CP56Time2a | + | +
| C_SE_TC_1(63) | Setpoint command, short value (FLOAT32) with CP56Time2a| + | +
| C_BO_TA_1(64) | Bitstring command (32 bit bitstring) with CP56Time2a | + | +

| C_IC_NA_1(100) | Interrogation command | + | +
| C_CI_NA_1(101) | Counter interrogation command | + | +
| C_RD_NA_1(102) | Read command | + | +
| C_CS_NA_1(103) | Clock synchronization command | + | +
| C_RP_NA_1(105) | Reset process command | + | +
| C_CD_NA_1(106) | Delay acquisition command | + | +

| P_ME_NA_1(110) | Parameter of measured values, normalized value | + | +
| P_ME_NB_1(111) | Parameter of measured values, scaled value  | + | +
| P_ME_NC_1(112) | Parameter of measured values, short floating point number | + | +
| P_AC_NA_1(113) | Parameter for activation | + | +
|==========================

=== IEC 60870-5-104 parameters

The following parameters are stored in *T104ConnectionParameter* objects.

.IEC 60870-5-104 parameters
[width="90%",cols="n,10",frame="topbot",options="header"]
|==========================
|Parameter        |Description
|k       |Number of unconfirmed APDUs in I format. Sender will stop transmission after k unconfirmed I messages.
|w       |Number of unconfirmed APDUs in I format. Receiver will confirm latest after w messages
|t0      |Timeout for connection establishment (in s)
|t1      |Timeout for transmitted APDUs in I/U format (in s) when timeout elapsed without confirmation the connection will be closed. This is used by the sender to determine if the receiver has failed to confirm a message.
|t2      |Timeout to confirm messages (in s). This timeout is used by the receiver to determine the time when the message confirmation has to be sent.
|t3      |time until test telegrams will be sent in case of an idle connection
|==========================
